// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK_1z4mAyJ5KSFTiPP9Coh-mqk0AvjHKo',
    appId: '1:599361383872:web:93647297aa54927cbcac25',
    messagingSenderId: '599361383872',
    projectId: 'jini-firebase',
    authDomain: 'jini-firebase.firebaseapp.com',
    storageBucket: 'jini-firebase.appspot.com',
    measurementId: 'G-4Y731JK465',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjbiA3KWacle6qfn54-OnO5DseNAQJBU8',
    appId: '1:599361383872:android:788e6f2e8488f19bbcac25',
    messagingSenderId: '599361383872',
    projectId: 'jini-firebase',
    storageBucket: 'jini-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCW_Ulix5CfQfkDrMbehFIvS6H1s9_0gl0',
    appId: '1:599361383872:ios:373c375f03a376e2bcac25',
    messagingSenderId: '599361383872',
    projectId: 'jini-firebase',
    storageBucket: 'jini-firebase.appspot.com',
    iosClientId: '599361383872-uhcolr0dkrkr1o94v7vbr9k3p3pnel4k.apps.googleusercontent.com',
    iosBundleId: 'com.example.jini',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCW_Ulix5CfQfkDrMbehFIvS6H1s9_0gl0',
    appId: '1:599361383872:ios:373c375f03a376e2bcac25',
    messagingSenderId: '599361383872',
    projectId: 'jini-firebase',
    storageBucket: 'jini-firebase.appspot.com',
    iosClientId: '599361383872-uhcolr0dkrkr1o94v7vbr9k3p3pnel4k.apps.googleusercontent.com',
    iosBundleId: 'com.example.jini',
  );
}
